# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbpXfhZIfa6puOCdFScxBUeEPCJXpXDz
"""

dna = input("Enter DNA sequence: ")
dna = dna.upper()
length = len(dna)

print("DNA sequence is:", dna)
print("Dna length :", length)


valid_bases = set("ATGC")
if set(dna).issubset(valid_bases):
  print("Vaid DNA is : Yes")

  a = 0
  t = 0
  g = 0
  c = 0
  for base in dna:
    if base == "A":
            a += 1

    elif base == "T":
            t += 1

    elif base == "G":
            g += 1

    elif base == "C":
            c += 1

  print("A:", a)
  print("T:", t)
  print("G:", g)
  print("C:", c)

  gc = calculate_gc_content(dna)
  at = calculate_at_content(dna)

  print(f"GC Content: {gc:.2f}%")
  print(f"AT Content: {at:.2f}%")

  print("Complement:", get_complement(dna))
  print("Reverse Complement:", get_reverse_complement(dna))


else:
    print("Valid DNA is : No")

